---
# from: https://docs.docker.com/engine/install/linux-postinstall/
- name: Create the docker group.
  group:
    name: docker
    state: present
  become: true

- name: Add your user to the docker group.
  user:
    name: "{{ ansible_env.USER }}"
    groups: docker
    append: yes
  become: true
  # notify: Reboot
