# sch: https://www.google.com/search?q=rpm-ostree+install+docker
# https://blog.2to.fun/en/posts/install-docker-in-silverblue/

- name: Install Docker
  community.general.rpm_ostree_pkg:
    name: "{{ item }}"
    state: present
  loop:
  - docker
  become: true
  notify: Reboot

- meta: flush_handlers

- name: Enable & Start Docker
  ansible.builtin.systemd_service:
    name: docker
    state: started
    enabled: true
  become: true