- name: pre
  apt:
    pkg:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
  # become: yes

- name: Add Docker’s official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  # become: yes

- name: add ansible repo
  apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
  # become: yes

- name: install
  apt:
    pkg:
    - docker-ce
    - docker-ce-cli
    - containerd.io
  # become: yes

# prime. docs.docker.com/engine/install/ubuntu/
