- name: Create the docker group.
  group:
    name: docker
    state: present
  become: yes

- name: Add your user to the docker group.
  user:
    name: me
    groups: docker
    append: yes
  become: yes

# https://docs.docker.com/engine/install/linux-postinstall/
