- name: ostree add repo
  ansible.builtin.shell: ostree remote add docker-ce https://download.docker.com/linux/fedora/docker-ce.repo
  args:
    creates: /etc/ostree/remotes.d/docker-ce.conf
  become: true
  notify: rpm-ostree cleanup
