---
- name: Create the docker group.
  group:
    name: docker
    state: present
  become: true

- name: Add your user to the docker group.
  user:
    name: "{{ ansible_env.USER }}"
    groups: docker
    append: yes
  become: true
