- hosts: localhost
  roles:
    - name: geerlingguy.docker
      become: true

    # to add non-root user permissions https://docs.docker.com/engine/install/linux-postinstall/
    - name: UniInc.Docker-User-Permission
